### PR TITLE
Update library dependencies

### PR DESCRIPTION
**Pull request by chrgraefe**
Updated library dependencies of StackExchange.Redis and Novell.Directory.Ldap.NETStandard

### CODE REVIEW

**Comment by Nordes** [comment]
Hi Christian, 

Thank you for your PR. However, the build failed 

> [xUnit.net 00:00:01.11]     IdentityServer.LdapExtension.Unit.UserStores.InMemoryUserStoreTests.ActiveDirectoryAttributeDisplayNameIsNull_SetsAppUserDisplayNameNull [FAIL]
>   X IdentityServer.LdapExtension.Unit.UserStores.InMemoryUserStoreTests.ActiveDirectoryAttributeDisplayNameIsNull_SetsAppUserDisplayNameNull [12ms]
>   Error Message:
>    System.Collections.Generic.KeyNotFoundException : The given key 'displayName' was not present in the dictionary.
>   Stack Trace:
>      at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
>    at IdentityServer.LdapExtension.UserModel.ActiveDirectoryAppUser.SetBaseDetails(LdapEntry ldapEntry, String providerName) in C:\projects\identityserver4-ldapextension\IdentityServer.LdapExtension\UserModel\ActiveDirectoryAppUser.cs:line 129
>    at IdentityServer.LdapExtension.Unit.UserStores.InMemoryUserStoreTests.ActiveDirectoryAttributeDisplayNameIsNull_SetsAppUserDisplayNameNull() in C:\projects\identityserver4-ldapextension\IdentityServer.LdapExtension.Unit\UserStores\InMemoryUserStoreTests.cs:line 133
> Test Run Failed.
> Total tests: 9
>      Passed: 8
>      Failed: 1
>  Total time: 2.7629 Seconds
> 

Could you look into it?

**Comment by chrgraefe** [comment]
You are right, this test case is failing, but i can'T see why. Has the behaviour changed for this case?

**Comment by chrgraefe** [comment]
Yeah, I had a look into the Novell.Directory.Ldap.NETStandard libary.
The behaviour of method "GetAttribute" has been changed.

actual: https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/blob/master/src/Novell.Directory.Ldap.NETStandard/LdapAttributeSet.cs

old: https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/blob/ef06c2f359e75be59f3963f59598a0ba3c7c5383/src/Novell.Directory.Ldap.NETStandard/LdapAttributeSet.cs

**Comment by chrgraefe** [comment]
@Nordes : Can you have a look at the test? The conditions have to be changed due to changed behavior of the Ldap library

**Comment by Nordes** [comment]
Thank's, I'll look up in the repo this week. I've got more time than before. I'll maybe updates some other parts.

**Comment by Nordes** [comment]
Actually, that`s the commit where they changed the implementation: 
https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/commit/6fb4289a2d63ba04ff5d77fe95a5e2c11b55e607#diff-d8f2aa64ea5f6400163c6f62be947a25

It's a pity they don't do a TryGetValue in their new implementation and return null if it does not exists. At least the behavior would not have been changed. Now we have to do some kind of try/catch to handle such behavior.

**Comment by Nordes** [comment]
I've fixed the implementation in master branch. I added a `GetNullableAttribute` extension method for `LdapEntry` object type. This way, it avoids throwing the Key not found exception and respect the previous behavior.

**Pull request merged**
